package tutor_agent

import (
	"bufio"
	"context"
	"errors"
	"fmt"
	"math"
	"ollama-demo/hnsw"
	"os"
	"path/filepath"
	"strings"

	"github.com/smallnest/langgraphgo/graph"
	"github.com/tmc/langchaingo/embeddings"
	"github.com/tmc/langchaingo/llms"
	"github.com/tmc/langchaingo/llms/openai"
)

// For test: /Users/wangyang/gitclonefiles/datafusion/README.md

type LLMType int

const (
	OpenAI LLMType = iota
	Ollama
)

type DocumentChunk struct {
	Content  string            // 切片内容
	Source   string            // 来源文件
	ChunkID  int               // 切片ID
	Metadata map[string]string // 元数据
}

// Tutor agent state definition
type TutorState struct {
	// Documents contents
	DocumentContents map[string]string

	// Document chunks and vector index
	DocumentChunks []DocumentChunk

	// HNSW Vector Index
	VectorIndex *hnsw.HNSWIndex

	// Embedding model
	Embedder embeddings.Embedder

	// 新增：NodeID 到 Chunk 索引的映射
	NodeIDToChunkIndex map[int]int

	// Generated by the Agent
	DocumentSummary string

	// Chat history
	Messages []llms.MessageContent

	// User input
	UserInput string

	// Whether the agent should continue
	ShouldContinue bool

	// Current teaching stage
	Stage string
}

type TutorAgent struct {
	model     llms.Model
	embedder  embeddings.Embedder
	graph     *graph.StateRunnable[TutorState]
	scanner   *bufio.Scanner
	dimension int // Embedding dimension
}

func NewTutorAgent(llmType LLMType) (*TutorAgent, error) {
	switch llmType {
	case OpenAI:
		return nil, errors.New("unsupported LLM type: OpenAI")
	case Ollama:
		return newOllamaTutorAgent()
	default:
		return nil, errors.New(fmt.Sprintf("unrecognized LLM type: %d", llmType))
	}
}

func newOllamaTutorAgent() (*TutorAgent, error) {
	// Config Ollama
	model, err := openai.New(
		openai.WithBaseURL("http://localhost:11434/v1"),
		openai.WithModel("deepseek-r1:14b"),
		openai.WithToken("ollama"),
	)
	if err != nil {
		return nil, fmt.Errorf("create LLM failed: %v", err)
	}

	embeddingLLM, err := openai.New(
		openai.WithBaseURL("http://localhost:11434/v1"),
		openai.WithToken("ollama"),
		openai.WithModel("nomic-embed-text"),
		openai.WithEmbeddingModel("nomic-embed-text"),
	)
	if err != nil {
		return nil, fmt.Errorf("create embedding LLM failed: %v", err)
	}

	embedder, err := embeddings.NewEmbedder(embeddingLLM)
	if err != nil {
		return nil, fmt.Errorf("create embedder failed: %v", err)
	}

	agent := &TutorAgent{
		model:     model,
		embedder:  embedder, // 初始化 embedder
		scanner:   bufio.NewScanner(os.Stdin),
		dimension: 768, // nomic-embed-text 的维度是 768
	}

	if err := agent.buildGraph(); err != nil {
		return nil, err
	}

	return agent, nil
}

func (t *TutorAgent) buildGraph() error {
	g := graph.NewStateGraph[TutorState]()

	// 1. Load documents node
	g.AddNode("load_documents", "load documents", t.loadDocuments)

	g.AddNode("vectorize_documents", "vectorize documents", t.vectorizeDocuments)

	// 2. Analyze documents node
	g.AddNode("analyze_documents", "analyze documents", t.analyzeDocuments)

	// 3. Chat node
	g.AddNode("chat", "chat", t.chatWithRAG)

	// Set edges
	g.AddEdge("load_documents", "vectorize_documents")    // 改为先向量化
	g.AddEdge("vectorize_documents", "analyze_documents") // 向量化后再分析
	g.AddEdge("analyze_documents", "chat")

	// no need the check continue node anymore
	// g.AddEdge("chat", "check_continue")

	// Conditional edge: decide the flow based on whether the user wants to continue
	g.AddConditionalEdge("chat", func(ctx context.Context, state TutorState) string {
		if state.ShouldContinue {
			return "chat" // continue chatting
		}
		return graph.END // end the session
	})

	// Set entry point
	g.SetEntryPoint("load_documents")

	// Compile the graph
	runnable, err := g.Compile()
	if err != nil {
		return err
	}

	t.graph = runnable
	return nil
}

func (t *TutorAgent) loadDocuments(ctx context.Context, state TutorState) (TutorState, error) {
	fmt.Println("\n📚 === 智能助教系统（RAG 增强版）===") // ✨ 修改：标题加上 RAG 标识
	fmt.Println("我可以帮助你深入学习和理解文档内容！")
	fmt.Println("💡 使用向量搜索技术，精准检索相关内容") // ✨ 新增：提示 RAG 功能
	fmt.Println()

	// 获取文件路径
	fmt.Print("请输入要学习的文档路径（多个文件用逗号分隔）: ")
	if !t.scanner.Scan() {
		return state, fmt.Errorf("读取输入失败")
	}

	pathsInput := strings.TrimSpace(t.scanner.Text())
	if pathsInput == "" {
		return state, fmt.Errorf("未提供文档路径")
	}

	// 解析路径
	paths := strings.Split(pathsInput, ",")
	state.DocumentContents = make(map[string]string)

	// 加载每个文件
	for _, path := range paths {
		path = strings.TrimSpace(path)
		content, err := t.loadFile(path)
		if err != nil {
			fmt.Printf("⚠️  加载文件 %s 失败: %v\n", path, err)
			continue
		}
		state.DocumentContents[path] = content
		fmt.Printf("✅ 已加载: %s (%d 字符)\n", filepath.Base(path), len(content))
	}

	if len(state.DocumentContents) == 0 {
		return state, fmt.Errorf("没有成功加载任何文档")
	}

	state.Stage = "documents_loaded"
	state.Embedder = t.embedder // ✨ 新增：将 embedder 存入 state
	return state, nil
}

// loadFile 加载单个文件
func (t *TutorAgent) loadFile(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	return string(data), nil
}

// chunkText - 文档切块
func (t *TutorAgent) chunkText(text string, chunkSize int, overlap int) []string {
	// 按段落分割
	paragraphs := strings.Split(text, "\n\n")

	var chunks []string
	var currentChunk strings.Builder
	currentSize := 0

	for _, para := range paragraphs {
		para = strings.TrimSpace(para)
		if para == "" {
			continue
		}

		paraSize := len(para)

		// 如果当前段落加上已有内容超过 chunkSize，保存当前 chunk
		if currentSize > 0 && currentSize+paraSize > chunkSize {
			chunks = append(chunks, currentChunk.String())

			// 保留 overlap 部分
			chunkText := currentChunk.String()
			if len(chunkText) > overlap {
				currentChunk.Reset()
				currentChunk.WriteString(chunkText[len(chunkText)-overlap:])
				currentChunk.WriteString("\n\n")
				currentSize = overlap
			} else {
				currentChunk.Reset()
				currentSize = 0
			}
		}

		currentChunk.WriteString(para)
		currentChunk.WriteString("\n\n")
		currentSize += paraSize
	}

	// 添加最后一个 chunk
	if currentSize > 0 {
		chunks = append(chunks, currentChunk.String())
	}

	return chunks
}

// vectorizeDocuments - 向量化文档
func (t *TutorAgent) vectorizeDocuments(ctx context.Context, state TutorState) (TutorState, error) {
	fmt.Println("\n🔄 正在处理文档...")

	// 创建 HNSW 索引
	state.VectorIndex = hnsw.NewHNSW(hnsw.Config{
		M:              16,
		EfConstruction: 200,
		Dimension:      t.dimension,
		DistanceFunc:   hnsw.CosineDistance, // 使用余弦距离
	})
	fmt.Printf("✅ 创建向量索引 (dimension=%d)\n", t.dimension)

	// 切块参数
	chunkSize := 500 // 每块约 500 字符
	overlap := 50    // 重叠 50 字符

	state.DocumentChunks = []DocumentChunk{}
	// 新增：创建 NodeID 到 Chunk 索引的映射
	nodeIDToChunkIndex := make(map[int]int) //
	chunkID := 0

	// 处理每个文档
	for path, content := range state.DocumentContents {
		fmt.Printf("\n📄 处理文档: %s\n", filepath.Base(path))

		// 切分文档
		chunks := t.chunkText(content, chunkSize, overlap)
		fmt.Printf("   切分为 %d 个块\n", len(chunks))

		// 向量化每个块
		for i, chunkText := range chunks {
			// 生成 embedding
			vector, err := state.Embedder.EmbedQuery(ctx, chunkText)
			if err != nil {
				fmt.Printf("⚠️  块 %d 向量化失败: %v\n", i, err)
				continue
			}

			// 转换为 float32
			vector32 := make([]float32, len(vector))
			for j, v := range vector {
				vector32[j] = float32(v)
			}

			// 添加到 HNSW 索引
			nodeID, err := state.VectorIndex.Add(vector32)
			if err != nil {
				fmt.Printf("⚠️  块 %d 添加到索引失败: %v\n", i, err)
				continue
			}

			// 记录映射关系
			chunkIndex := len(state.DocumentChunks)
			nodeIDToChunkIndex[nodeID] = chunkIndex

			// 保存块信息
			chunk := DocumentChunk{
				Content: chunkText,
				Source:  filepath.Base(path),
				ChunkID: chunkID,
				Metadata: map[string]string{
					"source": filepath.Base(path),
					"nodeID": fmt.Sprintf("%d", nodeID),
				},
			}
			state.DocumentChunks = append(state.DocumentChunks, chunk)
			chunkID++

			if (i+1)%10 == 0 || i == len(chunks)-1 {
				fmt.Printf("   进度: %d/%d 块已向量化\n", i+1, len(chunks))
			}
		}
	}

	// 在返回前保存映射表
	state.NodeIDToChunkIndex = nodeIDToChunkIndex

	fmt.Printf("\n✅ 向量化完成！总共处理 %d 个文档块\n", len(state.DocumentChunks))
	state.Stage = "vectorization_complete"
	return state, nil
}

// analyzeDocuments 使用 AI 分析文档内容
func (t *TutorAgent) analyzeDocuments(ctx context.Context, state TutorState) (TutorState, error) {
	fmt.Println("\n🔍 正在分析文档内容...")
	totalChars := 0
	for _, content := range state.DocumentContents {
		totalChars += len(content)
	}

	// 构建文档内容摘要
	var docsBuilder strings.Builder
	docsBuilder.WriteString("以下是需要学习的文档内容：\n\n")

	processedChars := 0
	fileCount := 0
	totalFiles := len(state.DocumentContents)

	for path, content := range state.DocumentContents {
		fileCount++
		fmt.Printf("📄 处理文件 [%d/%d]: %s\n", fileCount, totalFiles, filepath.Base(path))

		docsBuilder.WriteString(fmt.Sprintf("=== 文件: %s ===\n", filepath.Base(path)))

		// 如果文档太长，截取前面部分
		contentToAdd := content
		if len(content) > 2000 {
			contentToAdd = content[:2000]
			docsBuilder.WriteString(contentToAdd)
			docsBuilder.WriteString("\n\n[文档内容过长，已截取前 2000 字符]\n\n")
		} else {
			docsBuilder.WriteString(contentToAdd)
			docsBuilder.WriteString("\n\n")
		}

		processedChars += len(content)
		progress := float64(processedChars) / float64(totalChars) * 100
		fmt.Printf("   ⏳ 加载进度: %.1f%% (%d/%d 字符)\n", progress, processedChars, totalChars)
	}

	fmt.Println("\n✅ 文件加载完成，正在提交给助教分析...")

	// 让 AI 分析文档
	analysisPrompt := docsBuilder.String() + fmt.Sprintf(`

文档已被切分为 %d 个块并向量化，支持智能检索。

请作为一位专业的助教，完成以下任务：
1. 简要概述这些文档的主要内容和核心概念
2. 列出文档中的重点知识点
3. 说明你将如何帮助学习者理解这些内容

请用友好、易懂的语言回复。`, len(state.DocumentChunks))

	messages := []llms.MessageContent{
		llms.TextParts(llms.ChatMessageTypeHuman, analysisPrompt),
	}

	fmt.Println() // 换行，让输出更清晰
	fmt.Println("🤖 助教正在深度分析文档...")
	fmt.Println(strings.Repeat("-", 60))

	var summaryBuilder strings.Builder
	var isThinking bool
	var charCount int

	response, err := t.model.GenerateContent(ctx, messages,
		llms.WithTemperature(0.7),
		llms.WithMaxTokens(2000),
		llms.WithStreamingFunc(func(ctx context.Context, chunk []byte) error {
			text := string(chunk)

			// 检测思考过程标记
			if strings.Contains(text, "<think>") {
				isThinking = true
				fmt.Print("💭 助教思考: ")
				return nil
			}
			if strings.Contains(text, "</think>") {
				isThinking = false
				fmt.Println("")
				return nil
			}

			// 输出思考过程或最终内容
			if isThinking {
				fmt.Print(text)
			} else {
				// 过滤掉标签
				cleanText := strings.ReplaceAll(text, "<think>", "")
				cleanText = strings.ReplaceAll(cleanText, "</think>", "")
				if cleanText != "" {
					summaryBuilder.WriteString(cleanText)
					charCount += len(cleanText)
					fmt.Print(cleanText)
				}
			}

			return nil
		}),
	)
	if err != nil {
		return state, fmt.Errorf("分析文档失败: %v", err)
	}

	// 如果有流式输出，使用 summaryBuilder 的内容，否则使用 response
	if summaryBuilder.Len() > 0 {
		state.DocumentSummary = summaryBuilder.String()
	} else {
		state.DocumentSummary = response.Choices[0].Content
	}

	state.Messages = []llms.MessageContent{
		llms.TextParts(llms.ChatMessageTypeSystem,
			fmt.Sprintf(`你是一位专业的助教，帮助学习者深入理解文档内容。

文档已被切分为 %d 个块并向量化存储。
当回答问题时，系统会自动检索最相关的文档片段提供给你。

你的任务是：
1. 基于检索到的相关内容回答学习者的问题
2. 提供深入的解释和示例
3. 引导学习者思考和探索
4. 用清晰、友好的语言交流

请基于提供的上下文回答问题。`, len(state.DocumentChunks))),
		llms.TextParts(llms.ChatMessageTypeAI, state.DocumentSummary),
	}

	fmt.Println("\n" + strings.Repeat("=", 60))
	fmt.Printf("✅ 分析完成！文档已准备就绪（%d 个向量块）\n", len(state.DocumentChunks))
	fmt.Println(strings.Repeat("=", 60))
	fmt.Println("\n💡 提示：输入 'quit' 或 'exit' 可以退出")

	state.Stage = "analysis_complete"
	state.ShouldContinue = true
	return state, nil
}

// 新增函数：retrieveRelevantChunks - 检索相关文档块
func (t *TutorAgent) retrieveRelevantChunks(ctx context.Context, state TutorState, query string, topK int) ([]DocumentChunk, error) {
	// 将查询向量化
	queryVector, err := state.Embedder.EmbedQuery(ctx, query)
	if err != nil {
		return nil, fmt.Errorf("查询向量化失败: %v", err)
	}

	// 转换为 float32
	queryVector32 := make([]float32, len(queryVector))
	for i, v := range queryVector {
		queryVector32[i] = float32(v)
	}

	// 在 HNSW 索引中搜索
	results, err := state.VectorIndex.Search(queryVector32, topK, 100)
	if err != nil {
		return nil, fmt.Errorf("向量搜索失败: %v", err)
	}

	// 获取对应的文档块
	var relevantChunks []DocumentChunk
	for _, result := range results {
		// ✨ 使用映射表获取正确的索引
		chunkIndex, exists := state.NodeIDToChunkIndex[result.ID]
		if !exists {
			fmt.Printf("⚠️  警告：NodeID %d 在映射表中不存在\n", result.ID)
			continue
		}

		if chunkIndex >= 0 && chunkIndex < len(state.DocumentChunks) {
			chunk := state.DocumentChunks[chunkIndex] // ⭐ 使用映射后的索引
			similarity := 1.0 - result.Distance/2.0
			chunk.Metadata["similarity"] = fmt.Sprintf("%.4f", similarity)
			relevantChunks = append(relevantChunks, chunk)
		} else {
			fmt.Printf("⚠️  警告：映射后的索引 %d 超出范围 [0, %d)\n", chunkIndex, len(state.DocumentChunks))
		}
	}

	return relevantChunks, nil
}

// 新增函数：chatWithRAG - 支持 RAG 的对话交互
// （替代原来的 chat 函数）
func (t *TutorAgent) chatWithRAG(ctx context.Context, state TutorState) (TutorState, error) {
	// 获取用户输入
	fmt.Print("\n💬 你的问题: ")
	if !t.scanner.Scan() {
		state.ShouldContinue = false
		return state, nil
	}

	userInput := strings.TrimSpace(t.scanner.Text())
	state.UserInput = userInput

	// 检查退出命令
	if userInput == "quit" || userInput == "exit" {
		state.ShouldContinue = false
		fmt.Println("\n👋 感谢使用智能助教系统！祝学习愉快！")
		return state, nil
	}

	// 如果用户直接回车（空输入），提示重新输入
	if userInput == "" {
		fmt.Println("⚠️  请输入您的问题，或输入 'quit'/'exit' 退出")
		state.ShouldContinue = true
		return state, nil
	}

	// ✨✨✨ 新增：RAG 检索相关文档块 ✨✨✨
	fmt.Print("🔍 检索相关内容...")
	relevantChunks, err := t.retrieveRelevantChunks(ctx, state, userInput, 3)
	if err != nil {
		fmt.Printf("\n⚠️  检索失败: %v，将使用一般知识回答\n", err)
		relevantChunks = []DocumentChunk{}
	} else {
		fmt.Printf(" 找到 %d 个相关片段\n", len(relevantChunks))
	}

	// ✨✨✨ 新增：构建增强的提示词 ✨✨✨
	var contextBuilder strings.Builder
	contextBuilder.WriteString("基于以下相关文档内容回答问题：\n\n")

	for i, chunk := range relevantChunks {
		similarity := chunk.Metadata["similarity"]
		contextBuilder.WriteString(fmt.Sprintf("--- 相关片段 %d (相似度: %s, 来源: %s) ---\n",
			i+1, similarity, chunk.Source))
		contextBuilder.WriteString(chunk.Content)
		contextBuilder.WriteString("\n\n")
	}

	contextBuilder.WriteString(fmt.Sprintf("问题: %s\n\n", userInput))
	contextBuilder.WriteString("请基于上述相关内容，给出准确、详细的回答。如果上述内容不足以回答问题，请说明并尽可能提供帮助。")

	// ✨ 修改：添加用户消息时使用增强的上下文
	state.Messages = append(state.Messages,
		llms.TextParts(llms.ChatMessageTypeHuman, contextBuilder.String()))

	fmt.Println() // 换行

	var responseBuilder strings.Builder
	var isThinking bool
	var hasStartedOutput bool

	response, err := t.model.GenerateContent(ctx, state.Messages,
		llms.WithTemperature(0.7),
		llms.WithMaxTokens(3000),
		llms.WithStreamingFunc(func(ctx context.Context, chunk []byte) error {
			text := string(chunk)

			// 检测思考过程的开始标记
			if strings.Contains(text, "<think>") {
				isThinking = true
				fmt.Print("💭 助教思考: ")
				hasStartedOutput = true
				return nil
			}

			// 检测思考过程的结束标记
			if strings.Contains(text, "</think>") {
				isThinking = false
				fmt.Println("")
				fmt.Print("🎓 助教: ")
				return nil
			}

			// 输出思考过程或最终答案
			if isThinking {
				// 打印思考过程（过滤标签）
				cleanText := strings.ReplaceAll(text, "<think>", "")
				fmt.Print(cleanText)
			} else {
				// 输出最终答案
				if !hasStartedOutput {
					fmt.Print("🎓 助教: ")
					hasStartedOutput = true
				}
				// 过滤标签
				cleanText := strings.ReplaceAll(text, "</think>", "")
				if cleanText != "" {
					fmt.Print(cleanText)
					responseBuilder.WriteString(cleanText)
				}
			}

			return nil
		}),
	)
	if err != nil {
		fmt.Printf("\n❌ 生成回复失败: %v\n", err)
		// 即使出错也继续对话
		state.ShouldContinue = true
		return state, nil
	}

	fmt.Println() // 回复结束后换行

	// ✨✨✨ 新增：显示引用来源 ✨✨✨
	if len(relevantChunks) > 0 {
		fmt.Println("\n📚 引用来源:")
		for i, chunk := range relevantChunks {
			similarity := chunk.Metadata["similarity"]
			fmt.Printf("  [%d] %s (相似度: %s)\n", i+1, chunk.Source, similarity)
		}
	}

	// 获取 AI 回复内容
	var aiResponse string
	if responseBuilder.Len() > 0 {
		aiResponse = responseBuilder.String()
	} else {
		aiResponse = response.Choices[0].Content
	}

	// 添加 AI 回复到历史
	state.Messages = append(state.Messages,
		llms.TextParts(llms.ChatMessageTypeAI, aiResponse))

	// ✨✨✨ 新增：限制历史消息长度，避免过长 ✨✨✨
	if len(state.Messages) > 21 { // 1 system + 1 initial AI + 20 messages (10 轮对话)
		state.Messages = append(state.Messages[:2], state.Messages[len(state.Messages)-20:]...)
	}

	// 继续对话循环
	state.ShouldContinue = true
	state.Stage = "chat_complete"
	return state, nil
}

// chat 对话交互 - 支持多轮对话
func (t *TutorAgent) chat(ctx context.Context, state TutorState) (TutorState, error) {
	// 获取用户输入
	fmt.Print("\n💬 你的问题: ")
	if !t.scanner.Scan() {
		state.ShouldContinue = false
		return state, nil
	}

	userInput := strings.TrimSpace(t.scanner.Text())
	state.UserInput = userInput

	// 检查退出命令
	if userInput == "quit" || userInput == "exit" {
		state.ShouldContinue = false
		fmt.Println("\n👋 感谢使用智能助教系统！祝学习愉快！")
		return state, nil
	}

	// 如果用户直接回车（空输入），提示重新输入
	if userInput == "" {
		fmt.Println("⚠️  请输入您的问题，或输入 'quit'/'exit' 退出")
		state.ShouldContinue = true
		return state, nil
	}

	// 添加用户消息
	state.Messages = append(state.Messages,
		llms.TextParts(llms.ChatMessageTypeHuman, userInput))

	// 修改为：
	fmt.Println() // 换行

	var responseBuilder strings.Builder
	var isThinking bool
	var hasStartedOutput bool

	response, err := t.model.GenerateContent(ctx, state.Messages,
		llms.WithTemperature(0.7),
		llms.WithMaxTokens(3000),
		llms.WithStreamingFunc(func(ctx context.Context, chunk []byte) error {
			text := string(chunk)

			// 检测思考过程的开始标记
			if strings.Contains(text, "<think>") {
				isThinking = true
				fmt.Print("💭 助教思考: ")
				hasStartedOutput = true
				return nil
			}

			// 检测思考过程的结束标记
			if strings.Contains(text, "</think>") {
				isThinking = false
				fmt.Println("")
				fmt.Print("🎓 助教: ")
				return nil
			}

			// 输出思考过程或最终答案
			if isThinking {
				// 打印思考过程（过滤标签）
				cleanText := strings.ReplaceAll(text, "<think>", "")
				fmt.Print(cleanText)
			} else {
				// 输出最终答案
				if !hasStartedOutput {
					fmt.Print("🎓 助教: ")
					hasStartedOutput = true
				}
				// 过滤标签
				cleanText := strings.ReplaceAll(text, "</think>", "")
				if cleanText != "" {
					fmt.Print(cleanText)
					responseBuilder.WriteString(cleanText)
				}
			}

			return nil
		}),
	)
	if err != nil {
		fmt.Printf("\n❌ 生成回复失败: %v\n", err)
		// 即使出错也继续对话
		state.ShouldContinue = true
		return state, nil
	}

	fmt.Println() // 回复结束后换行示

	// 获取 AI 回复内容
	var aiResponse string
	if responseBuilder.Len() > 0 {
		aiResponse = responseBuilder.String()
	} else {
		aiResponse = response.Choices[0].Content
	}

	// 添加 AI 回复到历史
	state.Messages = append(state.Messages,
		llms.TextParts(llms.ChatMessageTypeAI, aiResponse))

	// 继续对话循环
	state.ShouldContinue = true
	state.Stage = "chat_complete"
	return state, nil
}

// Run 运行助教系统
func (t *TutorAgent) Run() error {
	ctx := context.Background()

	// 初始化状态
	initialState := TutorState{
		DocumentContents:   make(map[string]string),
		DocumentChunks:     []DocumentChunk{},
		NodeIDToChunkIndex: make(map[int]int),
		Messages:           []llms.MessageContent{},
		ShouldContinue:     true,
		Stage:              "init",
		VectorIndex:        nil,
		Embedder:           nil,
	}

	_, err := t.graph.Invoke(ctx, initialState)
	if err != nil {
		return fmt.Errorf("执行失败: %v", err)
	}

	return nil
}

// 新增函数：cosineSimilarity - 余弦相似度计算
// （用于验证，可选）
func cosineSimilarity(a, b []float32) float64 {
	if len(a) != len(b) {
		return 0
	}

	var dotProduct, normA, normB float64
	for i := range a {
		dotProduct += float64(a[i]) * float64(b[i])
		normA += float64(a[i]) * float64(a[i])
		normB += float64(b[i]) * float64(b[i])
	}

	if normA == 0 || normB == 0 {
		return 0
	}

	return dotProduct / (math.Sqrt(normA) * math.Sqrt(normB))
}
