package tutor_agent

import "github.com/tmc/langchaingo/llms"

// Tutor agent state definition
type TutorState struct {
	// Documents contents
	DocumentContents map[string]string
	// Generated by the Agent
	DocumentSummary string
	// Chat history
	Messages []llms.MessageContent
	// User input
	UserInput string
	// Whether the agent should continue
	ShouldContinue bool
	// Current teaching stage
	Stage string
}
